services:
  application:
    image: express-seed
    ports:
      - "3001:3001"
    configs: 
      - source: docker
        target: ./express_seed/config/docker.json

    #secrets: #TODO: Decide if server password should be a secret, or all of config should?

  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: express-server
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - type: volume
        source: db-volume
        target: /var/lib/postgresql/data

    
volumes:
  db-volume:
  
configs:
  docker:
    file: ./config/docker.json

  #secrets:
